In [5]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([[1,2] , [3,4]])
print(arr2)

arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
arr4 = np.zeros((4,5))# inside is the dimension of the array
print(arr4)

# These zero are naturally as float so if we want the int thne we have to specify the data types

arr5 = np.zeros((3,4), dtype=int)
print(arr5)

# same can be done in ones

arr6 = np.ones((3,4))
print(arr6)

arr7 = np.full((3,4) ,fill_value=7)
print(arr7)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [14]:
arr8 =np.empty((2,4))
print(arr8)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.00386346e-321 3.11525958e-307 1.24610723e-306]]


In [15]:
# The eye function creates the identity matrix, 
# that is, a matrix with elements on the diagonal are set to one, 
# and non-diagonal elements are set to zero

arr9 = np.eye(5, dtype=int)
print(arr9)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# The arange function works like the range function,
# but produces an array instead of a list.

arr10 = np.arange(0,10,2)
print(arr10)

# For non-integer ranges it is better to use linspace

arr11 = np.linspace(0,np.pi,5) # Evenly spaced range with 5 elements
print(arr11)

# With linspace one does not have to compute the length of the step, 
# but instead one specifies the wanted number of elements. By default, 
# the endpoint is included in the result, unlike with arange

[0 2 4 6 8]
[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [18]:
arr12 = np.random.random((3,4))          # Elements are uniformly distributed from half-open interval [0.0,1.0)

arr13 = np.random.normal(0, 1, (3,4))    # Elements are normally distributed with mean 0 and standard deviation

arr14 = np.random.randint(-2, 10, (3,4))  # Elements are uniformly distributed integers from the half-open interval [-2,10)

print(arr12)
print(arr13)
print(arr14)

[[0.63409866 0.5603483  0.55396973 0.08067615]
 [0.58513021 0.67884369 0.91643262 0.60502665]
 [0.58532121 0.65984097 0.72322541 0.08555021]]
[[-0.19663864  1.37580691 -1.24380647  0.12246678]
 [-0.03624327  0.47066329 -0.63679655  0.51945408]
 [-0.51360794 -0.82990046  0.69968009 -0.65913905]]
[[-1  9  1  4]
 [ 3  2  9  8]
 [-2  3  6  2]]


In [22]:
# so these random are generated different everytime we run it so we can use what is called seed
# so evertime it will give same output

np.random.seed(0)
print(np.random.randint(0, 100, 10))
print(np.random.normal(0, 1, 10))

# The call to np.random.seed initializes the global random number generator. 
# The calls np.random.random, np.random.normal, etc all use this global random number generator. 
# It is however possible to create new random number generators, 
# and use those to sample random numbers from a distribution.

new_generator = np.random.RandomState(seed=123)  # RandomState is a class, so we give the seed to its constructor
new_generator.randint(0, 100, 10)


[44 47 64 67 67  9 83 21 36 87]
[ 1.26611853 -0.50587654  2.54520078  1.08081191  0.48431215  0.57914048
 -0.18158257  1.41020463 -0.37447169  0.27519832]


array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47], dtype=int32)

In [ ]:
def info(name, a):
    print(f"{name} has dim {a.ndim}, shape {a.shape}, size {a.size}, and dtype {a.dtype}:")
    print(a)

# size give total number of elements in an array.

b=np.array([[1,2,3], [4,5,6]])
info("b", b)

b has dim 2, shape (2, 3), size 6, and dtype int64:
[[1 2 3]
 [4 5 6]]


In [25]:
# now create a 3-D array

c = np.array([b,b])
info("c",c)

d=np.array([[1,2,3,4]])                # a row vector
info("d", d)

c has dim 3, shape (2, 2, 3), size 12, and dtype int64:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
d has dim 2, shape (1, 4), size 4, and dtype int64:
[[1 2 3 4]]


In [ ]:
# Last dimension: Printed left to right (like a regular Python list: [1 2 3 4]).

# Second-to-last dimension: Printed top to bottom (each row appears on a new line).

# Higher dimensions: Also printed top to bottom, with each "slice" (sub-array) separated by an empty line for clarity



In [ ]:
import numpy as np
def get_rows(a):
    row = a.shape[0]
    col = a.shape[1]

    elements  = []
    for i in range(row):
        element = []
        for j in range(col):
           element.append(a[i][j])
        
        elements.append(element)
    

    
    return elements

# This will create a list of list which we don't want

def get_rows(a):
    elements = []
    for i in range(a.shape[0]):
        elements.append(a[i])  # Each a[i] is a 1D numpy array (row)
    return elements

    # list of 1d arary

def get_rows(a):
    return [row for row in a ]

def get_column(a):
    return [col for col in a.T]

def main():
    np.random.seed(0)
    a=np.random.randint(0,10, (4,4))
    print("a:", a)
    print("Rows:", get_rows(a))

if __name__ == "__main__":
    main()

a: [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Rows: [[np.int32(5), np.int32(0), np.int32(3), np.int32(3)], [np.int32(7), np.int32(9), np.int32(3), np.int32(5)], [np.int32(2), np.int32(4), np.int32(7), np.int32(6)], [np.int32(8), np.int32(8), np.int32(1), np.int32(6)]]


concatenate and stack. Concatenate takes n-dimensional arrays and <br>
returns an n-dimensional array, whereas stack takes <br>
 n-dimensional arrays and returns n+1-dimensional array.

In [14]:
a=np.arange(2)
b=np.arange(2,5)
print(f"a has shape {a.shape}: {a}")
print(f"b has shape {b.shape}: {b}")
np.concatenate((a,b))  # concatenating 1d arrays

c=np.arange(1,5).reshape(2,2)
print(c)
print(f"c has shape {c.shape}:", c, sep="\n")
np.concatenate((c,c))   # concatenating 2d arrays

# By default concatenate joins the arrays along axis 0. To join the arrays horizontally, add parameter axis=1

np.concatenate((c,c), axis=1)

# axis=0 → "down" (add rows)
# axis=1 → "across" (add columns)

# Use stack to create higher dimensional arrays from lower dimensional arrays

np.stack((b,b))

np.stack((b,b), axis=1)

a has shape (2,): [0 1]
b has shape (3,): [2 3 4]
[[1 2]
 [3 4]]
c has shape (2, 2):
[[1 2]
 [3 4]]


array([[2, 2],
       [3, 3],
       [4, 4]])

In [15]:
# Inverse operation of concatenate is split. Its argument specifies either the number of 
# equal parts the array is divided into, or it specifies explicitly the break points.

d=np.arange(12).reshape(6,2)
print("d:")
print(d)
d1,d2 = np.split(d, 2)
print("d1:")
print(d1)
print("d2:")
print(d2)

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
d1:
[[0 1]
 [2 3]
 [4 5]]
d2:
[[ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
d=np.arange(12).reshape(2,6)
print("d:")
print(d)

# split split at indces if you give more than obe value
parts=np.split(d, (2,3,5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


In [ ]:
def get_row_vectors(a):
    m = a.shape[0]
    n = a.shape[1]

    indices = list(range(1,m))
    return np.split(a,indices,axis=0)


    
def get_row_vector:
    return [a[i:i+1,:]for i in range(a.shape[0])]

def get_column_vector:
    return [a[:,j:j+1] for i in range(a.shape[1])]


# a[i:i+1, :] gives a 2D row vector of shape (1, n).
# a[:, j:j+1] gives a 2D column vector of shape (m, 1).

In [ ]:
n = 3
new_n = 2 * n - 1
main_arrn = np.eye(2 * n - 1,dtype = int)
anti_arrn = np.fliplr(main_arrn)

result = main_arrn + anti_arrn

result [result > 0] = 1

arrp = np.concatenate((result[new_n//2:,:],result[1:,:]))
arrp = arrp[0:new_n,:]
print(arrp)


[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]


In [59]:
# what we can do is using loops for the array is quite slow 
# so what we can do is vectorized operations\

a=np.array([2.1, 5.0, 17.2])
a2=a*2
print(a2)

b=np.array([-1, 3.2, 2.4])
print(-a**2 * b)

[ 4.2 10.  34.4]
[   4.41   -80.    -710.016]


In [60]:
print(np.abs(b))
print(np.cos(b))
print(np.exp(b))
print(np.log2(np.abs(b)))

[1.  3.2 2.4]
[ 0.54030231 -0.99829478 -0.73739372]
[ 0.36787944 24.5325302  11.02317638]
[0.         1.67807191 1.26303441]


In [61]:
np.random.seed(0)
a=np.random.randint(-100, 100, (4,5))
print(a)
print(f"Minimum: {a.min()}, maximum: {a.max()}")
print(f"Sum: {a.sum()}")
print(f"Mean: {a.mean()}, standard deviation: {a.std()}")

[[ 72 -53  17  92 -33]
 [ 95   3 -91 -79 -64]
 [-13 -30 -12  40 -42]
 [ 93 -61 -13  74 -12]]
Minimum: -91, maximum: 95
Sum: -17
Mean: -0.85, standard deviation: 58.39886557117355


In [62]:
np.random.seed(9)
b=np.random.randint(0, 10, (3,4))
print(b)
print("Column sums:", b.sum(axis=0))
print("Row sums:", b.sum(axis=1))

[[5 6 8 6]
 [1 6 4 8]
 [1 8 5 1]]
Column sums: [ 7 20 17 15]
Row sums: [25 19 15]


In [65]:
import numpy as np

def vector_angles(X, Y):
    # Dot product for each pair of vectors
    dot_product = np.sum(X * Y, axis=1)
    # Norms for each vector
    norm_X = np.linalg.norm(X, axis=1)
    norm_Y = np.linalg.norm(Y, axis=1)
    # Cosine of angles
    cos_angles = dot_product / (norm_X * norm_Y)
    # Clip for numerical stability
    cos_angles = np.clip(cos_angles, -1.0, 1.0)
    # Angle in radians
    angles_rad = np.arccos(cos_angles)
    # Convert to degrees
    angles_deg = np.degrees(angles_rad)
    return angles_deg

A=np.array([[0,0,1], [-1,1,0]])
B=np.array([[0,1,0], [1,1,0]])
a = vector_angles(A, B)

print(a)


[90. 90.]


Broadcasting <br>
We have seen that NumPy allows array operations that are performed element-wise.  <br>
But NumPy also allows binary operations that don't require the two arrays to have the same shape.

In [66]:
np.arange(3) + np.array([4])

array([4, 5, 6])

NumPy lines up shapes by adding 1’s to the left.

Each dimension must be either the same or 1.

If it’s 1, that value is repeated as needed.

If not, you get an error.